---
title: C++异常
author: 阿源
date: 2023/02/05 21:29
categories:
 - C++基础快速入门
tags:
 - C++
 - C++基础
 - 异常
---
# C++异常
## 异常的概述

遇到错误 抛出异常 捕获异常

异常：是指在程序运行的过程中发生的一些异常事件（如：除0溢出，数组下标越界，所要读取的文件不存在,空指针，内存不足，访问非法内存等等）。（异常是一个类）

c++异常机制相比C语言异常处理的优势?

​      函数的返回值可以忽略，但异常不可忽略。（忽略异常 程序结束）

​      整型返回值没有任何语义信息。而异常却包含语义信息，有时你从类名就能够体现出来

## 异常的抛出、捕获

```cpp
1 try
2 {
3 throw 异常值;
4 }
5 catch(异常类型1 异常值1)
6 {
7 处理异常的代码1;
8 }
9 catch(异常类型2 异常值2)
10 {
11 处理异常的代码2;
12 }
13 catch(...)//任何异常都捕获
14 {
15 处理异常的代码3;
16 }
```

## 栈解旋

异常被抛出后，从进入try块起，到异常被抛掷前，这期间在栈上构造的所有对象，都会被自动析构。析构的顺序与构造的顺序相反，这一过程称为栈的解旋

```cpp
1 try
2 {
3 Data ob1;
4 Data ob2;
5 Data ob3;
6 throw 1;//抛出异常后 ob3 ob2 ob1依次自动释放（栈解旋）
7 }
```

## 异常的接口声明

异常的接口声明：描述的是 可以抛出哪些类型的异常

```cpp
1 #include <iostream>
2
3 using namespace std;
4
5 //函数默认 可以抛出任何类型的异常（推荐）
6 void fun01()
7 {
8 //throw 1;
9 //throw '1';
10 throw "hello";
11
12 }
13 //只能抛出int,char异常
14 void fun02() throw(int,char)
15 {
16 //throw 1;
17 //throw '1';
18 throw "hello";//抛出 不能捕获
19 }
20
21 //不能抛出 任何异常
22 void fun03() throw()
23 {
24 throw 1;
25 //throw '1';
26 //throw "hello";//抛出 不能捕获
27 }
28
29 void test01()
30 {
31 int ret = 0;
32 try
33 {
34 fun03();
35 }
36 catch(int)//捕获
37 {
38 cout<<"int异常值为:"<<endl;
39 }
40 catch(char)//捕获
41 {
42 cout<<"char异常值为:"<<endl;
43 }
44 catch(const char *)//捕获
45 {
46 cout<<"const char *异常值为:"<<endl;
47 }
48
49 catch(...)//捕获
50 {
51 cout<<"其他异常值为:"<<endl;
52 }
53 }
54
55 int main(int argc, char *argv[])
56 {
57 test01();
58 return 0;
59 }
```

## 异常变量的生命周期

```cpp
1 class MyException
2 {
3 public:
4 MyException(){
5 cout << "异常变量构造" << endl;
6 };
7 MyException(const MyException & e)
8 {
9 cout << "拷贝构造" << endl;
10 }
11 ~MyException()
12 {
13 cout << "异常变量析构" << endl;
14 }
15 };
```

### 1、以普通对象 接异常值

![](https://cdn.jsdelivr.net/gh/clint-sfy/blogcdn@master/img/c_plus/异常1.png)

### 2、以对象指针 接异常值

![](https://cdn.jsdelivr.net/gh/clint-sfy/blogcdn@master/img/c_plus/异常2.png)

### 3、对象引用 接异常值（推荐）

![](https://cdn.jsdelivr.net/gh/clint-sfy/blogcdn@master/img/c_plus/异常3.png)

## 异常的多态

```cpp
1 //异常基类
2 class BaseException{
3 public:
4 virtual void printError(){};
5 };
6
7 //空指针异常
8 class NullPointerException : public BaseException{
9 public:
10 virtual void printError(){
11 cout << "空指针异常!" << endl;
12 }
13 };
14 //越界异常
15 class OutOfRangeException : public BaseException{
16 public:
17 virtual void printError(){
18 cout << "越界异常!" << endl;
19 }
20 };
21
22 void doWork(){
23
24 //throw NullPointerException();
25 throw OutOfRangeException();
26 }
27
28 void test03()
29 {
30 try{
31 doWork();
32 }
33 catch (BaseException& ex)//父类引用 可以捕获搭配该父类派生出的所有子类的子类
34 {
35 ex.printError();
36 }
37 }
```

## c++标准异常

![](https://cdn.jsdelivr.net/gh/clint-sfy/blogcdn@master/img/c_plus/异常4.png)

## 编写自己的异常

编写字节的异常：基于标准异常

自己的异常 一定要从exception上继承

```cpp
1 class NewException:public exception
2 {
3 private:
4 string msg;
5 public:
6 NewException(){}
7 NewException(string msg)
8 {
9 this‐>msg = msg;
10 }
11 //重写父类的what
12 virtual const char* what()const throw()//防止父类在子类前抛出标准异常
13 {
14 //将string类转换成char *
15 return this‐>msg.c_str();
16 }
17 ~NewException(){}
18 };
19
20 void test05()
21 {
22 try
23 {
24 throw NewException("哈哈，自己的异常");
25
26 }
27 catch(exception &e)
28 {
29 cout<<e.what()<<endl;
30 }
31 }
```

